pool:
    vmImage: macOS-12

parameters:
  - name: environment
    displayName: Configuration based on env
    type: string
    default: DEV
    values:
    - PROD
    - UAT
    - SIT
    - DEV
        
steps:
     
- task: NodeTool@0
  displayName: install node version
  inputs:
    versionSource: 'spec'
    versionSpec: '19.0'

- task: CmdLine@2
  displayName: install dependecies
  inputs:
    script: |
      npm install --ignore-scripts
      npm run build
      
- task: CmdLine@2
  displayName: npm build
  inputs:
    script: 'npm run ng build'

- task: CmdLine@2
  displayName: sync up android and iOS folder
  inputs:
    script: |
        npx cap sync

- task: InstallAppleCertificate@2
  displayName: install apple signing certificate
  inputs:
    certSecureFile: 'Certificates_Distribution.p12'
    certPwd: '123456'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  displayName: install apple provisioning profile
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Alpha_Recon_Mobile_Distribution.mobileprovision'

- task: CocoaPods@0
  displayName: install cocoapods
  inputs:
    workingDirectory: 'ios/App'
    forceRepoUpdate: true

- task: Xcode@5
  displayName: 'Building IPA File'
  inputs:
    actions: 'build archive'
    sdk: iphoneos
    xcWorkspacePath: 'ios/App/App.xcworkspace'
    scheme: 'App'
    packageApp: true
    signingOption: manual
    
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    teamId: '7GWKPZ38XK'
    xcodeVersion: "default"
  



- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactStagingDirectory)' 
  inputs:
    SourceFolder: '/Users/runner/work/1/s/output'
    Contents: '*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'